#!/usr/bin/env bash
set -euo pipefail

DESIRED_OWNER="0:0"

if [[ -d "${UMBREL_ROOT}" ]]; then
	owner=$(stat -c "%u:%g" "${UMBREL_ROOT}")

	if [[ "${owner}" != "${DESIRED_OWNER}" ]]; then
		chown "${DESIRED_OWNER}" "${UMBREL_ROOT}"
	fi
fi
